---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - sustainability.susk8s
  resources:
  - carboninfoes
  - emissionreports
  - workloadpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sustainability.susk8s
  resources:
  - carboninfoes/finalizers
  - emissionreports/finalizers
  - workloadpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - sustainability.susk8s
  resources:
  - carboninfoes/status
  - emissionreports/status
  - workloadpolicies/status
  verbs:
  - get
  - patch
  - update
